### ISSUE TITLE
Crash when converting to ACC

### ISSUE THREAD

**Issue by citizenserious** [caydey/ffshare#100]
**Describe the bug**

Wanted to convert a .mp3 to .acc and the app crashes when selecting the file

**Settings applied**
Does this happen on a clean install of the app or only when specific settings are changed

clean install with the only settings changed is "Audio file output extension" to ".acc"

**App Logs**
`FATAL EXCEPTION: main
Process: com.caydey.ffshare, PID: 27594
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.caydey.ffshare/com.caydey.ffshare.HandleMediaActivity}: java.lang.IllegalArgumentException: No enum constant k1.m.a.ACC
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.IllegalArgumentException: No enum constant k1.m.a.ACC
	at java.lang.Enum.valueOf(Enum.java:259)
	at k1.m$a.valueOf(Unknown Source:2)
	at k1.j.c(Unknown Source:1125)
	at com.caydey.ffshare.HandleMediaActivity.C(Unknown Source:198)
	at com.caydey.ffshare.HandleMediaActivity.onCreate(Unknown Source:52)
	at android.app.Activity.performCreate(Activity.java:8348)
	at android.app.Activity.performCreate(Activity.java:8327)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1421)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
	... 12 more`

**File used**
Uploading the file to help replicate the bug is very helpful however if it is not possible, run the following command on the file `ffprobe -v quiet -print_format json -show_format -show_streams  FILE` and include its output

I do not know how to do this, 
crash happens with any sound file, tried different ones with type .wav .mp3 even .acc

**Comment by caydey** [comment]
looks like AAC (Advanced Audio Coding) was spelt wrong.

**Comment by citizenserious** [comment]
> looks like AAC (Advanced Audio Coding) was spelt wrong.

Didn't even notice it myself while filing this issue :D
