### ISSUE TITLE
Crash on share

### ISSUE THREAD

**Issue by shuvashish76** [caydey/ffshare#102]
**Describe the bug**
App crashes when sharing an app to FFShare from gallery app. Intermittent crash...doesn't crash everytime.

**Settings applied**
Everything is set to its default settings. I haven't changed anything.

**Crash Logs**
```
FATAL EXCEPTION: main
Process: com.caydey.ffshare, PID: 7928
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.caydey.ffshare/com.caydey.ffshare.HandleMediaActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.lastIndexOf(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.lastIndexOf(java.lang.String)' on a null object reference
	at com.arthenica.ffmpegkit.FFmpegKitConfig.c(Unknown Source:93)
	at j1.j.c(Unknown Source:1337)
	at com.caydey.ffshare.HandleMediaActivity.C(Unknown Source:198)
	at com.caydey.ffshare.HandleMediaActivity.onCreate(Unknown Source:52)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	... 11 more

```
**Device details**
App version: 1.3.2 (21)
Model: Lenovo TB-8704X
Android: 9

**Comment by trulow** [comment]
I'm getting this same crash as well. Actually when trying to import any video, the app crashes.

**Comment by xandro0777** [comment]
See https://github.com/caydey/ffshare/issues/126#issuecomment-5391523380
