### ISSUE TITLE
The app crashes when selecting a video (Log+video included)

### ISSUE THREAD

**Issue by NikunjKhangwal** [caydey/ffshare#119]
**Describe the bug**
The app crashes as soon as i select a video, images seem to work fine

**Settings applied**
clean install

**App Logs**
`FATAL EXCEPTION: main
Process: com.caydey.ffshare, PID: 11918
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.caydey.ffshare/com.caydey.ffshare.HandleMediaActivity}: java.lang.IllegalArgumentException: No enum constant j1.l.a.LIBX264
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3993)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4180)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8601)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
Caused by: java.lang.IllegalArgumentException: No enum constant j1.l.a.LIBX264
	at java.lang.Enum.valueOf(Enum.java:300)
	at j1.l$a.valueOf(Unknown Source:2)
	at j1.l.b(Unknown Source:15)
	at j1.j.c(Unknown Source:2394)
	at com.caydey.ffshare.HandleMediaActivity.C(Unknown Source:198)
	at com.caydey.ffshare.HandleMediaActivity.onCreate(Unknown Source:52)
	at android.app.Activity.performCreate(Activity.java:8960)
	at android.app.Activity.performCreate(Activity.java:8938)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1530)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3975)
	... 13 more`

**File used**
https://github.com/user-attachments/assets/13968af2-d108-4503-8552-3f2112f9a542

**Comment by caydey** [comment]
I think this was fixed in the latest release v1.3.3 try upgrading your app version and let me know if it works

**Comment by NikunjKhangwal** [comment]
Yes it worked. Thanks
